local EnemyData = {

	LostSoul = {
		Name = "Lost Soul",
		EnemySubType = "Spirit",

		Attributes = {},
		Abilities = {},

		HealthScaling = 0.75,
		DamageScaling = 0.08,

		StageScaling = 1.05,

		MinStage = 1,
		MaxStage = 9,
		Weight = 50,
	},

	AshWisp = {
		Name = "Ash Wisp",
		EnemySubType = "Spirit",

		Attributes = {},
		Abilities = {},

		HealthScaling = 0.5,
		DamageScaling = 0.06,

		StageScaling = 1.08,

		MinStage = 1,
		MaxStage = 9,
		Weight = 40,
	},

	AbyssWanderer = {
		Name = "Abyss Wanderer",
		EnemySubType = "Abomination",

		Attributes = {},
		Abilities = {},

		HealthScaling = 0.9,
		DamageScaling = 0.05,

		StageScaling = 1.06,

		MinStage = 4,
		MaxStage = 9,
		Weight = 30,
	},
}

return EnemyData
